# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "centos/7"


  # Boxes will only be checked for updates to your curent version if
  # you run `vagrant box outdated`.
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
    v.customize ["modifyvm",:id,"--natdnsproxy1","off"]
    #v.gui = true
  end

  # The app is configured now to listen on this hostname
  config.vm.host_name = "centos.alexkubcaki.com"

  # Create a private nework (to be used for HA/scaling testing)
  # Add 'test.dev.getfilehub.com 192.168.111.10' to your hosts file
  # in order to connect from your host machine via DNS
  config.vm.network "private_network", ip: "192.168.111.11"


  # Share the repository folder to the guest VM.
  config.vm.synced_folder "../../../", "/git"


  # Provision
   config.vm.provision "shell", inline: <<-SHELL
   SHELL
end
