# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure(2) do |config|
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Uses the latest available cloud image of 16.04
  # https://www.ubuntu.com/cloud
  # https://cloud-images.ubuntu.com/xenial/current/
  config.vm.box = "ubuntu/xenial64"


  # Boxes will only be checked for updates to your curent version if
  # you run `vagrant box outdated`.
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |v|
    v.memory = 8192
    v.cpus = 4
    v.customize ["modifyvm",:id,"--natdnsproxy1","off"]
    #v.gui = true
  end

  # Requires the vagrant-disksize plugin
  config.disksize.size = '50GB'

  # The app is configured now to listen on this hostname
  config.vm.host_name = "ubuntu.alexkubcaki.com"

  # Create a private nework (to be used for HA/scaling testing)
  # Add 'test.dev.getfilehub.com 192.168.111.10' to your hosts file
  # in order to connect from your host machine via DNS
  config.vm.network "private_network", ip: "192.168.111.10"


  # Share the repository folder to the guest VM.
  config.vm.synced_folder "../../../", "/git"


  # docker-engine and docker-compose for Ubuntu
   config.vm.provision "shell", inline: <<-SHELL
     sudo sh /git/usernotfound/vagrant-dev-env/ubuntu/ubuntu-docker.sh
     sudo sh /git/usernotfound/vagrant-dev-env/ubuntu/ubuntu-bats.sh
     sudo sh /git/usernotfound/vagrant-dev-env/ubuntu/ubuntu-deps.sh
   SHELL
end
